### ISSUE TITLE
Methods notation

### ISSUE THREAD

**Issue by szepeviktor** [inpsyde/objects-hooks-remover#1]
Hello!

`Inpsyde\remove_object_hook` is usually written as `Inpsyde::remove_object_hook` even if it is not a static method.

Please consider mentioning methods this way in README.

e.g. see https://www.php.net/manual/en/book.datetime.php

**Comment by gmazzap** [comment]
Thanks @szepeviktor actually you are **not** correct. Method notation is used for... _methods_ the functions of this package are namespaced _functions_: `Inpsyde` here is a namespace not a class.

**Comment by szepeviktor** [comment]
Thank you for reminding me that there are no classes around here :)
